services:
  index:
    build: ./index
    restart: unless-stopped
    networks:
      - app-network
  solo:
    build: ./solo
    restart: unless-stopped
    networks:
      - app-network

  iptv:
    build: ./iptv
    restart: unless-stopped
    networks:
      - app-network

  media:
    build: ./media
    restart: unless-stopped
    volumes:
      - media-uploads:/app/uploads
    networks:
      - app-network
  
  projects:
    build: ./projects
    restart: unless-stopped
    networks:
      - app-network
  
  db:
   image: postgres:15-alpine
   env_file:
    - .env
   volumes:
    - postgres-data:/var/lib/postgresql/data
   networks:
    - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - index
      - media
      - solo
      - iptv
    networks:
      - app-network

volumes:
  postgres-data:
  media-uploads:

networks:
  app-network:
    driver: bridge