services:
  index:
    build: ./index
    networks:
      - app-network

  media:
    build: ./media
    depends_on:
      - db
    volumes:
      - media-uploads:/app/uploads
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - index
      - media
    networks:
      - app-network

  pgadmin:
  image: dpage/pgadmin4
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@example.com
    PGADMIN_DEFAULT_PASSWORD: senha_segura
  ports:
    - "5050:80"
  networks:
    - app-network

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
  media-uploads:

networks:
  app-network:
    driver: bridge